name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/node-ci.yml
  publish:
    uses: ./.github/workflows/node-publish-internal.yml
